config/routes.rb
Tablesorter::Application.routes.draw do

  resources :tables
  root :to => redirect('/tables')

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tablesorter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Bootstrap Template
    = stylesheet_link_tag 'application'
    = stylesheet_link_tag 'bootstrap.css'
    = stylesheet_link_tag 'bootstrap-responsive.css'

    =csrf_meta_tags

    /= javascript_include_tag 'jquery'
    /= javascript_include_tag 'jquery.tablesorter'
    = javascript_include_tag 'application'

  %body
    %div.navbar.navbar-inverse.navbar-fixed-top{:role => 'navigation'}
      %div.navbar-inner
        %div.container
          %button.btn-navbar{:type => 'button', 'data-toggle' => 'collapse', 'data-target' => '.nav-collapse'}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => '#'} Project Name
          %div.nav-collapse.collapse
            %ul.nav
              %li{:class => "#{'active' if current_page?(tables_path)}"}
                %a{:href => root_path} Home
              %li
                %a{:href => '#'} About
              %li
                %a{:href => '#'} Contact
    = yield

  /placed at the end of the document so the pages load quickly


  /= javascript_include_tag 'bootstrap'
  /= javascript_include_tag 'bootstrap-transition'
  /= javascript_include_tag 'bootstrap-alert'
  /= javascript_include_tag 'bootstrap-modal'
  /= javascript_include_tag 'bootstrap-dropdown'
  /= javascript_include_tag 'bootstrap-scrollspy'
  /= javascript_include_tag 'bootstrap-tab'
  /= javascript_include_tag 'bootstrap-tooltip'
  /= javascript_include_tag 'bootstrap-popover'
  /= javascript_include_tag 'bootstrap-button'
  /= javascript_include_tag 'bootstrap-collapse'
  /= javascript_include_tag 'bootstrap-carousel'
  /= javascript_include_tag 'bootstrap-typeahead'

app/views/tables/index.html.haml
%div.container
  %h1 testing

  %div.panel.panel-default
    %table.table.table-bordered.table-striped#main_data
      %thead
        %tr
          %th
            %div.headerCellDiv first name
          %th
            %div.headerCellDiv last name
          %th
            %div.headerCellDiv street address
          %th
            %div.headerCellDiv city
          %th
            %div.headerCellDiv state
          %th
            %div.headerCellDiv zip
          %th
            %div.headerCellDiv bar visits

        %tr
          %td.sorter-false
            %input.span2.colSearch#search1
          %td.sorter-false
            %input.span2.colSearch#search2
          %td.sorter-false
            %input.span2.colSearch#search3
          %td.sorter-false
            %input.span2.colSearch#search4
          %td.sorter-false
            %input.span2.colSearch#search5
          %td.sorter-false
            %input.span2.colSearch#search6
          %td.sorter-false
            %input.span2.colSearch#search7

      %tbody
        %tr
          %td.cell1 Frank
          %td.cell2 Vinci
          %td.cell3 802 N Monroe St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 3
        %tr
          %td.cell1 Joe
          %td.cell2 VW
          %td.cell3 251 E 6th St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 1
        %tr
          %td.cell1 Susan
          %td.cell2 Turner
          %td.cell3 627 N Monroe St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 1
        %tr
          %td.cell1 Amanda
          %td.cell2 Vinci
          %td.cell3 333 S Orange St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 7
        %tr
          %td.cell1 Ryan
          %td.cell2 Paul
          %td.cell3 251 E 6th St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 6
        %tr
          %td.cell1 Frank1
          %td.cell2 Vinci
          %td.cell3 802 N Monroe St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 3
        %tr
          %td.cell1 Joe1
          %td.cell2 VW
          %td.cell3 251 E 6th St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 1
        %tr
          %td.cell1 Susan1
          %td.cell2 Turner
          %td.cell3 627 N Monroe St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 1
        %tr
          %td.cell1 Amanda1
          %td.cell2 Vinci
          %td.cell3 333 S Orange St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 7
        %tr
          %td.cell1 Ryan1
          %td.cell2 Paul
          %td.cell3 251 E 6th St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 6
        %tr
          %td.cell1 Frank2
          %td.cell2 Vinci
          %td.cell3 802 N Monroe St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 3
        %tr
          %td.cell1 Joe2
          %td.cell2 VW
          %td.cell3 251 E 6th St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 1
        %tr
          %td.cell1 Susan2
          %td.cell2 Turner
          %td.cell3 627 N Monroe St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 1
        %tr
          %td.cell1 Amanda2
          %td.cell2 Vinci
          %td.cell3 333 S Orange St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 7
        %tr
          %td.cell1 Ryan2
          %td.cell2 Paul
          %td.cell3 251 E 6th St
          %td.cell4 Media
          %td.cell5 PA
          %td.cell6 19063
          %td.cell7 6
    %div.pager#pager
      %form
        %img.first{:src => 'http://mottie.github.com/tablesorter/addons/pager/icons/first.png'}
        %img.prev{:src => 'http://mottie.github.com/tablesorter/addons/pager/icons/prev.png'}
        %span.pagedisplay
        %img.next{:src => 'http://mottie.github.com/tablesorter/addons/pager/icons/next.png'}
        %img.last{:src => 'http://mottie.github.com/tablesorter/addons/pager/icons/last.png'}
        %select.pagesize
          %option{:selected => 'selected', :value => '10'} 10
          %option{:value => '20'} 20
          %option{:value => '30'} 30
          %option{:value => '40'} 40